doc: Update documentation related with test-targets-always-run feature
Flank/flank pull request #1136
Opened 2020-09-21 12:45 UTC by pawelpasterz

Fixes #1106 

This PR updates documentation for `test-targets-always-run` feature - test execution order is not guaranteed by flank.

2020-09-21 13:29 UTC, bootstraponline commented on README.md
> +  ## However flank doesn't guarantee tests execution order. It is specific for user's config and FTL internal implementation
I'd say something like this:

> Execution order is not guaranteed by Flank. Users are responsible for configuring their on device test runner logic.

2020-09-21 14:13 UTC, Sloox commented on README.md
> +  ## Execution order is not guaranteed by Flank. Users are responsible for configuring their on device test runner logic.
```suggestion
Execution order is not guaranteed by Flank. Users are responsible for configuring their own device test runner logic.
```

2020-09-21 14:13 UTC, Sloox commented on README.md
> +  ## Execution order is not guaranteed by Flank. Users are responsible for configuring their on device test runner logic.
```suggestion
  ## Execution order is not guaranteed by Flank. Users are responsible for configuring their on device test runner logic.
```

2020-09-21 14:15 UTC, Sloox requested changes
very minor mistakes 👍

2020-09-21 15:04 UTC, piotradamczyk5 approved these changes

2020-09-22 07:11 UTC, Sloox approved these changes

2020-09-22 07:11 UTC, merged