#685 add flank multi test targets example
Flank/flank pull request #1300
Opened 2020-11-05 11:31 UTC by jan-gogo

This PR adds FlankMultiTestTargetsExample required in #1281. 
Is created for reducing code review complexity of #1281.

2020-11-05 12:30 UTC, pawelpasterz approved these changes

2020-11-05 12:33 UTC, Sloox commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/AppDelegate.swift
> +
spacing?

2020-11-05 12:33 UTC, Sloox commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/AppDelegate.swift
> +
same here? extra spaces?

2020-11-05 12:33 UTC, Sloox commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/SceneDelegate.swift
> +
;)

2020-11-05 12:34 UTC, Sloox requested changes
remove some spaces?

2020-11-05 13:56 UTC, piotradamczyk5 approved these changes

2020-11-05 15:09 UTC, piotradamczyk5 commented
I changed title to **test:** prefix

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/UITests/UITests.swift
> +}
```suggestion
}

```

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/SecondUITests/SecondUITests.swift
> +}
```suggestion
}

```

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/SceneDelegate.swift
> +
```suggestion
```

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/SceneDelegate.swift
> +
```suggestion
```

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/AppDelegate.swift
> +
```suggestion
```

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/AppDelegate.swift
> +
```suggestion
```

2020-11-05 19:16 UTC, jan-gogo commented on test_projects/ios/FlankMultiTestTargetsExample/FlankMultiTestTargetsExample/ViewController.swift
> +
```suggestion
```

2020-11-06 06:46 UTC, piotradamczyk5 approved these changes

2020-11-06 07:52 UTC, Sloox approved these changes

2020-11-06 08:01 UTC, merged