ci: Added pre-commit-hook
Flank/flank pull request #1320
Opened 2020-11-16 09:24 UTC by Sloox

Fixes #1305

Needs to be tested. Locally to actually see a change. Simply try git commit and it should run detekt.

2020-11-16 16:17 UTC, piotradamczyk5 approved these changes

2020-11-17 08:20 UTC, jan-gogo requested changes
The linkHooks.sh was not executable so I have changed it using `chmod +x`.
After that, I have added empty lines to random kotlin file and tested pre-commit
```
MacBook-Pro-jan-gogo:flank-review jan-gogo$ git commit -m 'Test pre-commit'
hint: The '.githooks/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[#1305-git-hooks 19bd8833] Test pre-commit
 1 file changed, 9 insertions(+)
```
So I have changed `pre-commit` to executable and tried test again.
This is what I get:
```
MacBook-Pro-jan-gogo:flank-review jan-gogo$ git commit -m 'Test pre-commit'
fatal: cannot run .githooks//pre-commit: No such file or directory
```
Strange

2020-11-17 11:16 UTC, Sloox commented
> The `linkHooks.sh` was not executable so I have changed it using `chmod +x`.
> After that, I have added empty lines to a random kotlin file and tested pre-commit
> 
> ```
> MacBook-Pro-jan-gogo:flank-review jan-gogo$ git commit -m 'Test pre-commit'
> hint: The '.githooks//pre-commit' hook was ignored because it's not set as executable.
> hint: You can disable this warning with `git config advice.ignoredHook false`.
> [#1305-git-hooks 19bd8833] Test pre-commit
>  1 file changed, 9 insertions(+)
> ```
> 
> So I have changed `pre-commit` to executable and tried test again.
> This is what I get:
> 
> ```
> MacBook-Pro-jan-gogo:flank-review jan-gogo$ git commit -m 'Test pre-commit'
> fatal: cannot run .githooks//pre-commit: No such file or directory
> ```
> 
> Strange

Please retest it was a faulty shebang line.

2020-11-17 13:31 UTC, adamfilipow92 commented
Maybe we could add information about run ```linkHooks.sh``` before first commit to documentation in ```Environment setup``` section? It could help when for all new contributors. WDYT?

2020-11-17 14:51 UTC, piotradamczyk5 commented
One small issue on Mac
```
.githooks/linkHooks.sh: line 2: @echo: command not found
Changing git config for hooks to .githooks
Complete!
```

2020-11-17 14:53 UTC, piotradamczyk5 commented
> One small issue on Mac
> 
> ```
> .githooks/linkHooks.sh: line 2: @echo: command not found
> Changing git config for hooks to .githooks
> Complete!
> ```

I fixed it

2020-11-17 14:53 UTC, piotradamczyk5 approved these changes

2020-11-17 15:55 UTC, piotradamczyk5 commented on .githooks/linkHooks.sh
> +set echo of
```suggestion
set echo off
```

2020-11-17 15:55 UTC, piotradamczyk5 commented
> set echo off?

fixed

2020-11-17 17:54 UTC, jan-gogo approved these changes
I am not sure if `pre-commit` script will work on windows so `linkHooks.bat` probably is not necessary, but also I am not sure if any dev will use windows as the main os for development, so it's not a problem.

2020-11-17 18:03 UTC, merged

2020-11-18 09:35 UTC, Sloox commented
> I am not sure if `pre-commit` script will work on windows so `linkHooks.bat` probably is not necessary, but also I am not sure if any dev will use windows as the main os for development, so it's not a problem.

I use windows and it works correctly 👍