fix: Fix integration tests on CI
Flank/flank pull request #1410
Opened 2020-12-17 14:51 UTC by adamfilipow92

Fixes #1408 

## Test Plan
> How do we know the code works?

All IT should pass locally and on CI

## Checklist

- [X] Integration tests updated

2020-12-17 16:10 UTC, piotradamczyk5 commented
@Mergifyio rebase

2020-12-17 16:11 UTC, piotradamczyk5 commented
@flank-it

2020-12-18 10:57 UTC, Sloox approved these changes

2020-12-18 11:25 UTC, piotradamczyk5 requested changes
Waiting for fix all tests

2020-12-18 12:26 UTC, adamfilipow92 commented
@flank-it

2020-12-18 12:35 UTC, adamfilipow92 commented
@flank-it

2020-12-18 12:40 UTC, pawelpasterz commented
I think we should run IT again once https://github.com/Flank/flank/pull/1413 is merged (and this PR is rebased)

2020-12-18 12:58 UTC, piotradamczyk5 commented
@flank-it

2020-12-18 13:51 UTC, adamfilipow92 commented
@flank-it

2020-12-18 14:25 UTC, piotradamczyk5 approved these changes
Say no more
> **Integration tests succeed, you could see results [here](https://github.com/Flank/flank/actions/runs/430584995)**

2020-12-18 14:37 UTC, piotradamczyk5 commented
@Mergifyio rebase

2020-12-18 14:44 UTC, merged