refactor: Refactor data scratch-ipblocks
Flank/flank pull request #1811
Opened 2021-04-15 18:16 UTC by piotradamczyk5

Fixes #1746

## Test Plan
> How do we know the code works?

- Code is refactored according to the description in #1746
- command `flank ip-blocks list` runs without any problems

## Checklist

- [x] Unit tested

2021-04-16 10:32 UTC, jan-gogo requested changes
The files:
* IpBlocksToTable.kt
* ListIPBlocks.kt

are not a part of the adapters layer because they don't have any references to google API libs additionally they are widely used in the domain layer. According to the diagram below, the code from adapters cannot be used directly in the domain layer.

![architecture diagram](http://www.plantuml.com/plantuml/proxy?cache=no&fmt=svg&src=https://raw.githubusercontent.com/Flank/flank/master/docs/hld/flank-component-diagram.puml)

Please move back those two files to the `ftl.environment` and leave them for further domain refactor.

2021-04-16 10:32 UTC, jan-gogo commented on test_runner/src/main/kotlin/ftl/adapter/environment/ListIPBlocks.kt
> +fun ipBlocksList() = deviceIPBlocks().toIpBlocks()
```suggestion
fun ipBlocksList(): List<IpBlock> = deviceIPBlocks().toIpBlocks()
```

It's good to provide return type explicitly for public functions.
It makes the implementation a little bit easier to understand.

2021-04-16 11:12 UTC, jan-gogo commented
@piotradamczyk5 Sorry for the mistake, I have copy-pasted the wrong file name, should be `TestEnvironmentInfo.kt` instead of `ListIPBlocks.kt`

2021-04-16 11:13 UTC, jan-gogo requested changes
@piotradamczyk5 Sorry for the mistake, I have copy-pasted the wrong file name, should be TestEnvironmentInfo.kt instead of ListIPBlocks.kt

2021-04-16 13:46 UTC, piotradamczyk5 commented
> The files:
> 
> * IpBlocksToTable.kt
> * ~ListIPBlocks.kt~ TestEnvironmentInfo.kt
> 
> are not a part of the adapters layer because they don't have any references to google API libs additionally they are widely used in the domain layer. According to the diagram below, the code from adapters cannot be used directly in the domain layer.
> 
> ![architecture diagram](https://camo.githubusercontent.com/341a4b13c591f91344eff2adff8b92aef0d1bee49138599e52ad08d62b23bc93/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f70726f78793f63616368653d6e6f26666d743d737667267372633d68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f466c616e6b2f666c616e6b2f6d61737465722f646f63732f686c642f666c616e6b2d636f6d706f6e656e742d6469616772616d2e70756d6c)
> 
> Please move back those two files to the `ftl.environment` and leave them for further domain refactor.

For me data and adapter layers are badly named:
`adapter` layer is `data` while `data` is `adapter`

2021-04-16 13:51 UTC, jan-gogo commented
@piotradamczyk5 I do not agree. The adapter is an implementation that is adapting the library code or client implementation to the data structures and interfaces declared in the data layer.

2021-04-16 14:13 UTC, piotradamczyk5 commented
> @piotradamczyk5 I do not agree. The adapter is an implementation that is adapting the library code or client implementation to the data structures and interfaces declared in the data layer.

Discussed on slack with @jan-gogo . 
The new package structure will be 
`presentation` > `domain` > `api` > `adapter` > `client`

2021-04-16 14:20 UTC, jan-gogo approved these changes

2021-04-20 11:25 UTC, adamfilipow92 approved these changes

2021-04-20 11:25 UTC, merged