refactor: Structural output Android models describe
Flank/flank pull request #1887
Opened 2021-04-30 18:18 UTC by piotradamczyk5

Fixes #1846

## Test Plan
> How do we know the code works?

- Code is refactored according to #1846
- Android describe models command works like previously

## Checklist

- [x] Unit tested

2021-05-03 18:27 UTC, pawelpasterz approved these changes
Minor suggestion, LGTM!

2021-05-03 18:27 UTC, pawelpasterz commented on test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/AndroidModelDescribeCommand.kt
> +    override val out: Any.() -> Unit
```suggestion
    override val out = outputLogger { 
```

2021-05-04 07:02 UTC, Sloox requested changes
small required change from @pawelpasterz

2021-05-04 07:11 UTC, piotradamczyk5 commented
> small required change from @pawelpasterz

@Sloox fixed

2021-05-04 13:24 UTC, Sloox approved these changes

2021-05-04 13:24 UTC, merged