docs: Add user guide for Corellium MVP
Flank/flank pull request #1977
Opened 2021-05-28 11:50 UTC by jan-gogo

Fixes #1976 

[User guide](docs/flank_corellium.md)

2021-05-28 13:53 UTC, piotradamczyk5 requested changes
The issue described here #1979

2021-05-28 13:54 UTC, adamfilipow92 commented
When using this config.
```

apks:
  - path: "app-debug.apk"
    tests:
      - path: "app-single-success-debug-androidTest.apk"

```

I getting error

```

java -jar flank.jar corellium test android run -c="./flank_corellium.yml"
* Authorizing
* Parsing test cases
* Calculating shards
* Preparing output directory
Created /Users/adamfilipowicz/Repos/flank/test_runner/build/libs/results/corellium/android/2021-05-28_15-47-25-963
* Dumping shards
Created /Users/adamfilipowicz/Repos/flank/test_runner/build/libs/results/corellium/android/2021-05-28_15-47-25-963/android-shards.json
* Invoking devices
Getting instances already created by flank.
Obtained 1 already created devices
Wait until all instances are ready...
ready: 01e8d313-c907-4a3f-ad7d-c726cac6655e
All instances invoked and ready to use.
* Installing apks
Connecting agent for 01e8d313-c907-4a3f-ad7d-c726cac6655e
* Parsing apk info
* Executing tests
Getting console 01e8d313-c907-4a3f-ad7d-c726cac6655e
java.util.ServiceConfigurationError: io.ktor.client.HttpClientEngineContainer: Provider io.ktor.client.engine.cio.CIOEngineContainer not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:591)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1222)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1266)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1301)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1386)
        at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1293)
        at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1326)
        at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1317)
        at io.ktor.client.HttpClientJvmKt.<clinit>(HttpClientJvm.kt:39)
        at flank.corellium.client.agent.ConnectKt.connectAgent(Connect.kt:26)
        at flank.corellium.client.core.ApiKt.connectAgent(Api.kt:146)
        at flank.corellium.adapter.InstallAndroidAppsKt$installAndroidApps$1$1.invokeSuspend(InstallAndroidApps.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Total run duration: 0m 15s
 ✘ adamfilipowicz@MacBook-Pro-Adam  ~/Repos/flank/test_runner/build/libs   1976_Add_user_guide_for_Corellium_MVP  java -jar flank.jar corellium test android run -c="./flank_corellium.yml"
* Authorizing
* Parsing test cases
* Calculating shards
* Preparing output directory
Created /Users/adamfilipowicz/Repos/flank/test_runner/build/libs/results/corellium/android/2021-05-28_15-48-20-341
* Dumping shards
Created /Users/adamfilipowicz/Repos/flank/test_runner/build/libs/results/corellium/android/2021-05-28_15-48-20-341/android-shards.json
* Invoking devices
Getting instances already created by flank.
Obtained 1 already created devices
Wait until all instances are ready...
ready: 01e8d313-c907-4a3f-ad7d-c726cac6655e
All instances invoked and ready to use.
* Installing apks
Connecting agent for 01e8d313-c907-4a3f-ad7d-c726cac6655e
* Parsing apk info
* Executing tests
Getting console 01e8d313-c907-4a3f-ad7d-c726cac6655e
java.util.ServiceConfigurationError: io.ktor.client.HttpClientEngineContainer: Provider io.ktor.client.engine.cio.CIOEngineContainer not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:591)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1222)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1266)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1301)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1386)
        at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1293)
        at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1326)
        at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1317)
        at io.ktor.client.HttpClientJvmKt.<clinit>(HttpClientJvm.kt:39)
        at flank.corellium.client.agent.ConnectKt.connectAgent(Connect.kt:26)
        at flank.corellium.client.core.ApiKt.connectAgent(Api.kt:146)
        at flank.corellium.adapter.InstallAndroidAppsKt$installAndroidApps$1$1.invokeSuspend(InstallAndroidApps.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCorouti [...]

2021-05-31 05:58 UTC, Sloox reviewed
Fixes.

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +Run your tests in parallel on virtual devices driven by Corellium backend.
```suggestion
Run Android tests in parallel on virtual devices driven by the Corellium backend.
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +Run your tests in parallel on virtual devices driven by Corellium backend.
```suggestion
Run Android & iOS tests in parallel on virtual devices driven by Corellium backend.
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +The Flank - Corellium integration is at the MVP stage, so only core, most important features are available.
```suggestion
The Flank - Corellium integration is at the MVP stage, so only the core and most important features are available.
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +Flank is just a client-side application that can prepare the time-efficient parallel test plan to run on several devices. It requires a third-party provider that can serve a huge amount of devices to
```suggestion
Flank is just a client-side application that can prepare a time-efficient parallel test plan to run on several devices. It requires a third-party provider that can serve a huge amount of devices to run tests on them.   
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +* Provides technology to virtualize mobile operating systems on servers powered by ARM cores. - Which is giving incredible ability for scaling amount of devices.
```suggestion
* Provides technology to virtualize mobile operating systems on servers powered by ARM cores. - This gives an incredible ability for scaling with regards to the amount of devices.
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +* Gives access to the bare operating system (Android or iOS). - Which is allowing to run optimized sharding algorithm for improving test execution time and reducing costs.
```suggestion
* Gives access to the bare operating system (Android or iOS). - Which allows a run optimized sharding algorithm that improves test execution time and reduces costs.
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +Flank - Corellium integration is built in the `flank.jar` executable, so the latest Flank build is giving you access to the features driven on the Corellium backend.
```suggestion
Flank - Corellium integration is built in the `flank.jar` executable, so the latest Flank build gives you access to the features driven on the Corellium backend.
```

2021-05-31 05:58 UTC, Sloox commented on docs/flank_corellium.md
> +Instead of or along with configuration file you can specify same options, in a command-line, which will override config file options.
```suggestion
Instead of or along with configuration file you can specify some options, in a command-line, which will override config file options.
```

OR

```suggestion
These can be included alongside the configuration file. They will override or supplement the configuration file depending on the usage.
```

2021-05-31 09:54 UTC, jan-gogo commented on docs/flank_corellium.md
> +Run your tests in parallel on virtual devices driven by Corellium backend.
```suggestion
Run mobile tests in parallel on virtual devices driven by Corellium backend.
```

2021-05-31 09:58 UTC, jan-gogo commented
> Fixes.

Thanks!!! 👍

2021-05-31 10:44 UTC, adamfilipow92 approved these changes

2021-05-31 14:38 UTC, Sloox approved these changes

2021-05-31 14:39 UTC, merged