feat: Added firebase event to Mixpanel
Flank/flank pull request #2088
Opened 2021-07-16 13:37 UTC by adamfilipow92

Fixes #2087 

## Test Plan
> How do we know the code works?

Mixpanel shows new event, all tests pass.

## Checklist

- [X] Documented
- [X] Unit tested

2021-07-19 14:23 UTC, Sloox requested changes
Some changes :)

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +Flank is currently tracking event with following properties:
```suggestion
Flank is currently tracking events with the following properties:
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +This property contains version of schema, this property should be equals to this document version.
```suggestion
This property contains a schema version, it should be equal to this document version.
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +By these event's we can check how frequently users upgrade the Flank version.
```suggestion
With this event we can check how frequently users upgrade the Flank to a new version.
```
OR
```suggestion
With these event's we can check how frequently users upgrade their Flank to a new version.
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +This property contains id of project used in firebase.
```suggestion
This property contains the id of the project used in firebase.
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +This property contains information about count of tests and count of successful, failed and flaky tests.
```suggestion
This property contains information about overall count of tests and the count of successful, failed and flaky tests.
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +This property contains information about time of execution tests by device type (virtual, physical, total)
```suggestion
This property contains information about the time of execution of tests by device type (virtual, physical, total)
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +This property contains information about outcome of the entire run. More information you can find here: https://github.com/Flank/flank/blob/3a213579b0b8ed7ca018314f0619146408292b35/docs/feature/summa
```suggestion
This property contains information about the outcome of the entire run. More information you can find here: https://github.com/Flank/flank/blob/3a213579b0b8ed7ca018314f0619146408292b35/docs/feature/summary_output.md#possible-outputs
```

2021-07-19 14:23 UTC, Sloox commented on docs/flank_mixpanel_metrics.md
> +With these event's we can realize the report ```How many millions per month in spend is Flank responsible for on Firebase Test Lab? ```
```suggestion
With these event's we can realize the report ```How many millions per month is spent on Firebase Test lab by way of using Flank? ```
```

2021-07-21 07:23 UTC, Sloox approved these changes
I commited the changes and approved :+1:

2021-07-21 20:33 UTC, piotradamczyk5 approved these changes

2021-07-21 20:33 UTC, merged