Update gradle wrapper
Flank/flank pull request #2358
Opened 2023-04-03 22:16 UTC by kozaxinan

Fixes #

Called "./gradlew wrapper" to update gradle wrapper for the current version.

## Test Plan
> How do we know the code works?

gradle commands should work
.

## Checklist

- [ ] Documented
- [ ] Unit tested
- [ ] Integration tests updated

2023-04-27 20:25 UTC, Fry-kun commented
@flank-it

2023-04-27 23:28 UTC, kozaxinan commented
@flank-it

2023-04-27 23:54 UTC, Fry-kun requested changes

2023-04-27 23:54 UTC, Fry-kun commented on gradlew.bat
Seems to be using LF for line endings. Pretty sure Windows prefers CRLF.

2023-04-28 08:57 UTC, kozaxinan commented on gradlew.bat
<img width="389" alt="Screenshot 2023-04-28 at 10 56 33" src="https://user-images.githubusercontent.com/2559837/235103180-b07ed6aa-01dd-4c4c-856b-329a72b0818e.png">

It has windows line endings.

2023-04-28 18:53 UTC, Fry-kun commented on gradlew.bat
Sg, my diff probably confused me

2023-04-28 18:54 UTC, Fry-kun approved these changes

2023-04-28 20:30 UTC, merged